onmetal/onmetal-api

- config/controller/rbac/role.yaml
- controllers/networking/aliasprefix_controller.go
- controllers/networking/networkinterfacebind_controller.go
- Add missing rbac marker in aliasprefix controller
- Fix nil pointer dereference in network interface bind controller
/cc @nikhilbarge
> Add missing RBAC and fix nil pointer dereference

- .github/workflows/check-codegen.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/test.yml
- Dockerfile
- apis/common/v1alpha1/common_types.go
- apis/compute/machine_types.go
- apis/compute/machinepool_types.go
- apis/compute/register.go
- apis/compute/v1alpha1/machine_types.go
- apis/compute/v1alpha1/machinepool_types.go
- apis/compute/v1alpha1/register.go
- apis/ipam/register.go
- apis/ipam/v1alpha1/register.go
- apis/networking/register.go
- apis/networking/v1alpha1/register.go
- apis/storage/register.go
- apis/storage/v1alpha1/register.go
- controllers/ipam/prefix_controller.go
- docs/development/setup.md
- envtestutils/apiservice.go
- envtestutils/envtestutils.go
- generated/clientset/internalversion/fake/register.go
- generated/clientset/versioned/fake/register.go
- generated/clientset/versioned/scheme/register.go
- go.mod
- registry/compute/machineclass/strategy.go
- registry/compute/machinepool/strategy.go
- registry/storage/volumepool/strategy.go
Everything `goimports -w`ed since with go 1.19 this seems to cause issues otherwise.
> Fix update preparation & lint issues

- controllers/networking/network_protection_controller.go
Fix sporadic in network protection deletion flow.
> Fix network protection deletion flow

- admission/plugin/machinevolumedevices/admission.go
- admission/plugin/machinevolumedevices/admission_test.go
In case of an UPDATE, the volume device will now be reclaimed from the previous volume (if any).
Fixes #522
> Fix volume device names being updated

- apis/storage/validation/volumepool_test.go
- Use correct attribute path in test
> Fix typo in test

- config/controller/rbac/role.yaml
- onmetal-controller-manager/client/client.go
- onmetal-controller-manager/controllers/networking/aliasprefix_controller.go
- onmetal-controller-manager/controllers/networking/loadbalancer_controller.go
- onmetal-controller-manager/controllers/networking/loadbalancer_controller_test.go
- onmetal-controller-manager/controllers/networking/networkinterface_controller.go
- onmetal-controller-manager/controllers/networking/suite_test.go
- onmetal-controller-manager/controllers/networking/virtualip_controller.go
- onmetal-controller-manager/main.go
- Implements the `LoadBalancer` proposal:  https://github.com/onmetal/onmetal-api/blob/main/docs/proposals/03-loadbalancer.md
> Implement `LoadBalancer` controller

- onmetal-controller-manager/controllers/networking/loadbalancer_controller.go
- onmetal-controller-manager/controllers/networking/loadbalancer_controller_test.go
Fixing the missing NetworkRef in loadbalancerrouting. 
Fixes #557
> Fix LoadBalancerRouting Networkref population

- onmetal-controller-manager/main.go
- Register `Indexer` if `NetworkProtectionController` is enabled
> Add missing index

- onmetal-controller-manager/controllers/networking/network_protection_controller.go
- onmetal-controller-manager/main.go
> Fix typo in `Indexer`

- .golangci.yaml
- api/compute/v1alpha1/common.go
- api/storage/v1alpha1/common.go
- onmetal-apiserver/internal/apis/compute/common.go
- onmetal-apiserver/internal/apis/compute/v1alpha1/conversions.go
- onmetal-apiserver/internal/apis/compute/v1alpha1/register.go
- onmetal-apiserver/internal/apis/storage/common.go
- onmetal-apiserver/internal/apis/storage/v1alpha1/conversions.go
- onmetal-apiserver/internal/apis/storage/v1alpha1/register.go
- onmetal-apiserver/internal/app/app_test.go
- onmetal-apiserver/internal/registry/compute/machine/storage/storage.go
- onmetal-apiserver/internal/registry/compute/machine/strategy.go
- onmetal-apiserver/internal/registry/storage/volume/storage/storage.go
- onmetal-apiserver/internal/registry/storage/volume/strategy.go
> Implement field selectors for `poolRef` attributes

- api/storage/v1alpha1/volumepool_types.go
- onmetal-apiserver/internal/apis/storage/volumepool_types.go
- Rename `NotAvailable` to `Unavailable`
> Fix the `VolumePoolState`

- poollet/volumepoollet/cmd/volumepoollet/app/app.go
Add healthz check for event generator early
> Fix volumepoollet startup

- docs/proposals/07-quota.md
This proposal is about introducing a `ResourceQuota` type to manage and limit resource usage in `Namespace`s.
> Resource Quota Proposal

- .github/workflows/check-codegen.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/test.yml
- Dockerfile
- Makefile
- client-go/informers/factory.go
- client-go/onmetalapi/clientset.go
- docs/api-reference/overview.md
- docs/development/setup.md
- gen/v3/apis__compute.api.onmetal.de__v1alpha1_openapi.json
- gen/v3/apis__core.api.onmetal.de__v1alpha1_openapi.json
- gen/v3/apis__ipam.api.onmetal.de__v1alpha1_openapi.json
- gen/v3/apis__networking.api.onmetal.de__v1alpha1_openapi.json
- gen/v3/apis__storage.api.onmetal.de__v1alpha1_openapi.json
- go.mod
- go.sum
* Update to go 1.20
* Update all tools versions
* Regenerate all generated files
* Update necessary deps from `go.mod`
* Clean up `Makefile`
> Various dependency updates

- api/compute/v1alpha1/common.go
- api/storage/v1alpha1/common.go
- docs/api-reference/core.md
- internal/apis/compute/common.go
- internal/apis/compute/v1alpha1/conversions.go
- internal/apis/storage/common.go
- internal/apis/storage/v1alpha1/conversions.go
- internal/app/app_suite_test.go
- internal/app/compute_test.go
- internal/app/core_test.go
- internal/app/storage_test.go
- internal/registry/compute/machine/strategy.go
- internal/registry/storage/bucket/strategy.go
- internal/registry/storage/volume/strategy.go
* Allow selecting `Machine`s based on machine class
* Allow selecting `Volume`s based on volume class
* Allow selecting `Bucket`s based on bucket class
> Implement additional field selectors

- cmd/onmetal-controller-manager/main.go
- internal/client/compute.go
- internal/client/storage.go
- internal/controllers/compute/machineclass_controller.go
- internal/controllers/compute/suite_test.go
- internal/controllers/networking/suite_test.go
- internal/controllers/storage/bucketclass_controller.go
- internal/controllers/storage/suite_test.go
- internal/controllers/storage/volumeclass_controller.go
Update all `<kind>Class` controllers to use cache / the newly introduced field selectors.
> Enhance `<kind>Class` controllers

- internal/apis/networking/v1alpha1/defaults.go
- internal/apis/networking/v1alpha1/defaults_test.go
- internal/apis/networking/v1alpha1/v1alpha1_suite_test.go
> Fix network interface prefix length defaulting

- docs/proposals/10-network-policies.md
This proposal introduces the concept of network policies. Network policies are a declarative resource to specify how traffic inside `Network`s should be limited.
> Network policies proposal

- api/networking/v1alpha1/util.go
- internal/controllers/networking/loadbalancer_controller.go
- internal/controllers/networking/loadbalancer_controller_test.go
- Allocate IPAM Prefix IP for Internal LoadBalancer
- Add testcase to validate Internal LoadBalancer IP allocation
Fixes #760
> Implement internal IP allocation for Internal LoadBalancer

- .github/release-drafter.yml
- Add a new category "⚠️ Breaking" with a label "breaking"
> Add `breaking` category to release drafter configuration

- config/apiserver/etcd/etcd.yaml
change etcd listen ip address for support ipv4 and ipv6
> Change `listen-client-urls` in etcd `StatefulSet`

- .github/workflows/clean-cache.yml
Add GH workflow to clean cache artefacts once a PR is closed.
> Add GH workflow to clean cache artefacts once a PR is closed

- utils/envtest/apiservice.go
- utils/envtest/envtest.go
This introduces adding additional aggregated API servers to envtest extensions.
> Envtest: allow additional aggregated APIs

- poollet/machinepoollet/cmd/machinepoollet/app/app.go
- poollet/volumepoollet/cmd/volumepoollet/app/app.go
- Added missing indexer to `machinepoollet`
- Added missing indexer to `volumepoollet`
> Fix `Indexer`

- broker/machinebroker/server/status.go
- broker/volumebroker/server/status.go
- Fix `nil-pointer` in resource accumulation
> Fix resource accumulation

- broker/machinebroker/server/status.go
- broker/volumebroker/server/status.go
- Use correct volume class quantity key
> Fix `*-broker` Status

- hack/update-codegen.sh
- hack/update-proto.sh
Use `vgopath` setup consistently.
> Use `vgopath` setup consistently

- .github/workflows/lint.yml
- .golangci.yaml
- Makefile
- internal/admission/plugin/volumeresizepolicy/admission_test.go
- internal/app/compute_test.go
- internal/app/storage_test.go
- internal/controllers/compute/suite_test.go
- internal/controllers/core/core_suite_test.go
- internal/controllers/networking/network_protection_controller_test.go
- utils/context/context_test.go
- Add golangci-lint fetching in `Makefile`
- Add ginkgolinter to golangci linting configuration
- Fix existing gomega/ginkgo linting issues
> Improve linting in project
